app = "tikdownloader"

[build]
  dockerfile = "Dockerfile"
  context = "."

[http_service]
  internal_port = 8080
  force_https = true

[[http_service.checks]]
  path = "/health"
  method = "GET"





